### PR TITLE
Remove unused documentation

### PR DESCRIPTION
**Pull request by Seth-Rothschild**
Other documentation we should consider removing:
+ use_cases/index.rst 
+ use_cases/customer_segmentation.ipynb
+ use_cases/retail_data_demo.ipynb
+ guides/entitysets.ipynb

### CODE REVIEW

**Comment by kmax12** [comment]
@Seth-Rothschild looks like the PR only removes 2 of the 4 files

**Comment by Seth-Rothschild** [comment]
The PR removes fel.rst and use_cases.rst. There are 4 additional files that we might consider removing: 
+ use_cases/index.rst 
+ use_cases/customer_segmentation.ipynb
+ use_cases/retail_data_demo.ipynb
+ guides/entitysets.ipynb

**Comment by kmax12** [comment]
@Seth-Rothschild I read that too fast. let's remove those 4 as well.

**Comment by kmax12** [comment]
Looks good. Merging

**Pull request merged**
