### PR TITLE
Add readme to pypi page

### LINKED ISSUE #331: Fix Featuretools PyPI Page
The [current PyPI page](https://packaging.python.org/guides/making-a-pypi-friendly-readme/) for Featuretools doesn't how our readme.

There are some instructions to fix that here: https://packaging.python.org/guides/making-a-pypi-friendly-readme/

### PR DESCRIPTION
**Pull request by jeff-hernandez**
I updated `setup.py` to include `README.md`. Let me know if anything needs modification. Thanks.

### CODE REVIEW

**Comment by jeff-hernandez** [comment]
During continuous integration with Python 3.5, the shell doesn't seem to find the correct directory for the `README.md`. I used the suggested method below:
```
this_directory = path.abspath(path.dirname(__file__))
```
I get the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-omei4hwd/README.md'
```

I will experiment with different methods to input the `README.md`

**Comment by kmax12** [comment]
I would expect `__file__` to point to `__init__.py`, which is one level lower then the readme.

**Comment by jeff-hernandez** [comment]
On other python versions, there isn't an error with finding `open('README.md')`, but there is a problem in python version 3.5. The error occurs during the command `tox -e py35`.

**Comment by kmax12** [comment]
does it occur if you `pip install` in python 3.5 or is it specific to tox?

**Comment by jeff-hernandez** [comment]
It might be specific to tox. The occurs during the `tox` command in the continuous integration process on CircleCI.

**Comment by kmax12** [comment]
can you replicate locally with or without tox?

**Comment by jeff-hernandez** [comment]
I could try to replicate the same error locally with and without tox.

**Comment by jeff-hernandez** [comment]
Before replicating the error, I found a solution on [stackoverflow](https://stackoverflow.com/a/47941626/5386567). Essentially, we need to include the `README.md` inside the  `MANIFEST.in`. Let me know if anything needs modification. Thanks.

**Comment by kmax12** [comment]
good find. I just tested uploading it to the test pypi server: https://test.pypi.org/project/featuretools/0.4.2.dev0/. I can confirm it works. 

Merging now. Will go out in next release!

**Pull request merged**
