### PR TITLE
Add number of rows to plot of entityset

### LINKED ISSUE #722: Add number of rows to EntitySet.plot()
The repr of an `EntitySet` shows the number of rows. 

```python
import featuretools as ft
es = ft.demo.load_mock_customer(return_entityset=True)
es
```
```
Entityset: transactions
  Entities:
    transactions [Rows: 500, Columns: 5]
    products [Rows: 5, Columns: 2]
    sessions [Rows: 35, Columns: 4]
    customers [Rows: 5, Columns: 4]
  Relationships:
    transactions.product_id -> products.product_id
    transactions.session_id -> sessions.session_id
    sessions.customer_id -> customers.customer_id
```

The `.plot()` method is frequently preferred by users since it shows the same information and more visually, with the exception of the number of rows.

plot

To improve `.plot()`, we should decide on a way to add the number of rows to the output

### PR DESCRIPTION
**Pull request by MarcoGorelli**
### Pull Request Description
Add number of rows to graph of entityset, closes #722 

-----
*After creating the pull request: in order to pass the **changelog_updated** check you will need to update the "Future Release" section of* `docs/source/changelog.rst` *to include this pull request.*

### CODE REVIEW

**Comment by rwedge** [comment]
Would you be willing to add a test case that checks the number of rows reported in the graph and checks the single row edge case?

**Comment by MarcoGorelli** [comment]
Sure - will do!

**Comment by MarcoGorelli** [comment]
@rwedge How should graphviz output be tested? I've tried with a regular expression, please let me know if there's a better way / you'd like this done differently

**Comment by rwedge** [comment]
@MarcoGorelli the tests look good, thanks!  Could you add yourself the list of contributors for the upcoming release in the changelog?

**Comment by MarcoGorelli** [comment]
Happy to help, thank you for your tool!

**Pull request merged**
